services:
    anavaro.fbgcustom.listener:
        class: anavaro\fbgcustom\event\main_listener
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
        tags:
            - { name: event.listener }